name: Build on push

on:
  push:
    branches: **

jobs:
  build:
    strategy:
      matrix:
        node: ['12', '14', '16']
        os: ['ubuntu-latest', 'windows-latest']

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

      - name: Build and Test Success
        run: |
          echo "::set-output name=mix-test::$(cat test.log)"
        id: build_and_test_success
        env:
          MIX_ENV: test
          PGHOST: localhost
          PGUSER: postgres

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{join(steps.build_and_test_success.outputs.*, '\n')}}
          SLACK_TITLE: Test Results
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBOOK }}
