name: Actions On Push

on:
  push:
    branches: '**'

jobs:
  build:
    strategy:
      matrix:
        node: ['12', '14', '16']
        os: ['ubuntu-latest', 'windows-latest']

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
  slack:
    name: General Push Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions:/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ods-details
          SLACK_MESSAGE: 'Post Content'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
